name: Label Sync

on:
  issues:
  label:

jobs:
  labels:
    name: LabelSync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1.0.0
      - uses: lannonbr/issue-label-manager-action@2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}