name: Label Sync

on:
  issues:
  label:

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v1
    - name: Run Label Sync
      uses: crazy-max/ghaction-github-labeler@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}